# /etc/smcroute.conf

# 1. Allow Codec2 Voice Comm
mroute from br0 group 239.1.1.1 to bat0
mroute from bat0 group 239.1.1.1 to br0

# 2. Allow ATAK (Default ATAK Multicast groups)
mroute from br0 group 239.2.3.1 to bat0
mroute from bat0 group 239.2.3.1 to br0


mroute from br0 group 224.10.10.1 to bat0
mroute from bat0 group 224.10.10.1 to br0

# 3. Allow mDNS (Optional, for device discovery)
mroute from br0 group 224.0.0.251 to bat0
mroute from bat0 group 224.0.0.251 to br0